import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from "react";
import Link from "next/link";
import {signIn, signOut, useSession} from "next-auth/client/_utils"
export default function Home() {
  const [session, loading] = useSession(); 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
          Not signed in <br/>
          <button onClick={signIn}>Sign In</button>
          </>
        )}
        {session && (
          <>
          Signed in as {session.user.email}<br/>
          <div>You're in!</div>
          <button onClick={signOut}>Sign Out</button>
          </>
        )}
      </main>
    </div>
  )
}
